fix(grid-manager): fix height re-render
lets-talk/chat-utils pull request #120
Opened 2021-09-02 14:31 UTC by felipeegasneris

WIP

2021-09-03 22:42 UTC, felipeegasneris commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) bug input text en mobile](https://trello.com/c/yjcrcKwr/312-5-bug-input-text-en-mobile)

2021-09-06 14:34 UTC, alex-sysoev requested changes
PR is very difficult to review. When reviewing from `Files changed` all your changes are mixed with formatter and linter changes and are disordered. When reviewing commit by commit it is almost impossible because of multiple changes of the same files. Please use rebase interactive to order your PR o think about order and PR clarity beforehand.

2021-09-06 14:34 UTC, alex-sysoev commented on packages/grid-manager/src/grid/utils.ts
> +export const getHeightRulesFromViewport = (
Falta poner el tipo del valor que retorna la función, probablemente sera Boolean si entiendo bien, de acá sale la pregunta sobre el nombre de la función que se supone devuelve Rules cómo la otra mas abajo.

2021-09-06 14:34 UTC, alex-sysoev commented on packages/grid-manager/src/index.ts
> +      .onTransition((state, event) => {
Remove logs please.

2021-09-06 14:34 UTC, alex-sysoev commented on packages/grid-manager/src/widgetsMachine/actions.ts
> +      : context.renderCycle.updateCycle.update;
Por que tu asignas el update cycle a heightUpdate si no requiere height update ?

2021-09-07 22:10 UTC, merged